language: objective-c
before_install:
  - source ~/.rvm/scripts/rvm && rvm install 1.8.7-p358 && rvm use 1.8.7-p358
  - brew install cmake
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nHost bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
notifications:
  email: false
install: bundle install
script: bundle exec rake
